config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", include("edcar_distribuidora.core.urls", namespace="core"),),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("edcar_distribuidora.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

edcar_distribuidora/core/urls.py
from django.urls import path

from edcar_distribuidora.core import views

app_name = "core"
urlpatterns = [
    path("", views.home, name="home"),
    path("quem-somos/", views.quem_somos, name="quem_somos"),
    path("contato/", views.contato, name="contato"),
    path("categoria/<int:categoria_id>", views.itens_categoria, name="itens_categoria"),
]

edcar_distribuidora/users/urls.py
from django.urls import path

from edcar_distribuidora.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

edcar_distribuidora/core/models.py
from django.db import models

class AbstractModel(models.Model):
    nome = models.CharField('Nome', max_length=50,  unique=True)
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)
    ativo = models.BooleanField('Ativo(a)?', default=True)

    class Meta:
        abstract = True


class Loja(AbstractModel):

    def __str__(self):
        return '{}'.format(self.nome)

    class Meta:
        verbose_name = "Loja"
        verbose_name_plural = "Lojas"


class Catalogo(AbstractModel):
    loja = models.ForeignKey(Loja, verbose_name='loja', related_name='catalogos', on_delete=models.PROTECT)

    def __str__(self):
        return '{} - {}'.format(self.loja ,self.nome)

    class Meta:
        verbose_name = "Catálogo"
        verbose_name_plural = "Catálogos"


class Departamento(AbstractModel):

    def __str__(self):
        return '{}'.format(self.nome)

    class Meta:
        verbose_name = "Departamento"
        verbose_name_plural = "Departamentos"


class Categoria(AbstractModel):
    departamento = models.ForeignKey(Departamento, verbose_name='departamento', related_name='categorias', on_delete=models.PROTECT)

    def __str__(self):
        return '{}'.format(self.nome)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"


class Item(AbstractModel):
    categoria = models.ForeignKey(Categoria, verbose_name='categoria', related_name='itens', on_delete=models.PROTECT)
    catalogo = models.ForeignKey(Catalogo, verbose_name='catalogo', related_name='itens', on_delete=models.PROTECT)
    codigo = models.BigIntegerField('Código', unique=True)
    descricao = models.TextField('Descrição')
    valor = models.DecimalField('Valor (R$)', max_digits=10, decimal_places=2)
    mostrar_valor = models.BooleanField('Mostrar valor no catálogo?', default=False)
    imagem = models.ImageField(upload_to='item/imagens', verbose_name='Imagem',
                               null=True, blank=True)

    def __str__(self):
        return '{} - {} - {} - {}'.format(self.catalogo, self.categoria.departamento, self.categoria, self.nome)

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Itens"

edcar_distribuidora/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

edcar_distribuidora/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

edcar_distribuidora/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Departamento, Categoria, Item

def quem_somos(request):
    template_name = "core/quem_somos.html"
    context = {}
    return render(request, template_name, context)


def contato(request):
    template_name = "core/contato.html"
    context = {}
    return render(request, template_name, context)


def home(request):
    departamentos = Departamento.objects.filter(ativo=True)
    produtos = Item.objects.filter(ativo=True)
    template_name = "core/home.html"
    context = {
        'departamentos': departamentos,
        'produtos': produtos
    }
    return render(request, template_name, context)


def itens_categoria(request, categoria_id):
    departamentos = Departamento.objects.filter(categorias__isnull=False, ativo=True).distinct()
    produtos = Item.objects.filter(categoria_id=categoria_id)
    template_name = "core/itens_categoria.html"
    categoria = Categoria.objects.get(pk=categoria_id)
    context = {
        'departamentos': departamentos,
        'produtos': produtos,
        'categoria': categoria
    }
    return render(request, template_name, context)

edcar_distribuidora/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

edcar_distribuidora/core/templates/core/contato.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container" style="padding: 20px;">
        <div class="row">
            <div class="col-md-6 contact-clean">
                <form method="post">
                    <h2 class="text-center">Fale Conosco</h2>
                    <div class="form-group"><input class="form-control" type="text" name="nome" placeholder="Nome"></div>
                    <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Email"></div>
                    <div class="form-group"><textarea class="form-control" name="mensagen" placeholder="Mensagen" rows="14"></textarea></div>
                    <div class="form-group text-center"><button class="btn btn-primary" type="submit" style="background-color: rgb(222,55,58);">ENVIAR</button></div>
                </form>
            </div>
            <div class="col-md-6 align-self-center m-auto">
                <div class="row justify-content-center align-items-center">
                    <div class="col text-center align-self-center" style="padding: 10px;"><i class="fa fa-whatsapp" style="font-size: 78px;color: #25d366;"></i></div>
                </div>
                <div class="row">
                    <div class="col text-center" style="padding: 10px;"><a href="https://api.whatsapp.com/send?phone=556384400891" target="_blank"><img src="{% static 'img/qrscanner.gif' %}" style="width: 100%;"></a></div>
                </div>
                <div class="row">
                    <div class="col text-center">
                        <h2 class="text-center text-success">Fale diretamente pelo WhatsApp</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

edcar_distribuidora/core/templates/core/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row" style="margin-bottom: 20px;">
    <div class="col-md-12">
        <nav class="navbar navbar-light navbar-expand-md">
            <div class="container-fluid"><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-2"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navcol-2">
                    <ul class="nav navbar-nav mx-auto">
                    {% if departamentos.count > 0 %}
                        {% for departamento in departamentos %}
                            <li class="nav-item dropdown">
                                <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">{{ departamento }} </a>
                                <div class="dropdown-menu" role="menu">
                                    {% for categoria in departamento.categorias.all %}
                                        <a class="dropdown-item" role="presentation" href="{% url 'core:itens_categoria' categoria.pk %}">{{ categoria }}</a>
                                    {% endfor %}
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger d-flex justify-content-center" role="alert">
                            <span>Não existem produtos registrados</span>
                        </div>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>

{% if produtos.count > 0 %}
    <div class="text-center">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Home</li>
            </ol>
        </nav>
    </div>

    <div class="row articles" style="margin-bottom: 30px;">
        {% for produto in produtos %}
            <div class="col-sm-6 col-md-2 text-center item" style="padding:30px;">
                {% if produto.imagem %}
                <div class="row img-produto">
                    <a href="#"><img class="img-fluid" src="{{ produto.imagem.url }}"></a>
                </div>
                {% endif %}
                <div class="row name-produto">
                    <h6 class="name">{{ produto.nome }}</h6>
                </div>
                <div class="row desc-produto">
                    <p class="text-left description">{{ produto.descricao|truncatechars:200 }}</p>
                </div>
                <div class="row icon-produto">
                    <a class="action" href="#">
                        <i class="fa fa-search-plus"></i>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <div class="alert alert-danger d-flex justify-content-center" role="alert"> 
        <span>Não existem produtos registrados para essa categoria</span>
    </div>
{% endif %}
{% endblock %}

edcar_distribuidora/core/templates/core/itens_categoria.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="text-center">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="breadcrumb-link" href="{% url 'core:home' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ categoria.departamento.nome }}</li>
            <li class="breadcrumb-item active" aria-current="page">{{ categoria.nome }}</li>
        </ol>
    </nav>
</div>
{% if produtos.count > 0 %}
    <div class="row articles" style="margin-bottom: 30px;">
        {% for produto in produtos %}
            <div class="col-sm-6 col-md-2 text-center item" style="padding:30px;">
                <div class="row img-produto">
                    <a href="#"><img class="img-fluid" src="{{ produto.imagem.url }}"></a>
                </div>
                <div class="row name-produto">
                    <h6 class="name">{{ produto.nome }}</h6>
                </div>
                <div class="row desc-produto">
                    <p class="text-left description">{{ produto.descricao|truncatechars:200 }}</p>
                </div>
                <div class="row icon-produto">
                    <a class="action" href="#">
                        <i class="fa fa-search-plus"></i>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <div class="alert alert-danger d-flex justify-content-center" role="alert"> 
        <span>Não existem produtos registrados para essa categoria</span>
    </div>
{% endif %}
{% endblock %}

edcar_distribuidora/core/templates/core/quem_somos.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="article-clean">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
                    <div class="text-center intro">
                        <h1 class="text-center">Quem Somos</h1>
                        <img class="img-fluid" src="{% static 'img/desk.jpg' %}">
                    </div>
                    <div class="text">
                        <p style="text-align: justify;">A Ed Car Distribuidora atua no mercado automotivo desde 1996 e se destaca dos demais pelo seu atendimento eficaz, comprometimento, solidez e especialização em som e acessórios para auto.<br></p>
                        <p style="text-align: justify;">Procurando suprir a necessidade de nossos clientes com produtos de qualidade superior e preço justo, de diversos segmentos: loja de som e acessórios, concessionárias, auto elétrico, centros automotivos, entre outros, com excelência.
                            Temos em nosso extenso portifolio, apenas fornecedores com marcas consolidadas que garantem qualidade, segurança e credibilidade.<br></p>
                        <p style="text-align: justify;">Acredimentos que o nosso crescimento está fundamentado nos resultados obtidos por nossos clientes.<br></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

edcar_distribuidora/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Ed Car Distribuidora</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/Article-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'css/Article-Dual-Column.css' %}">
    <link rel="stylesheet" href="{% static 'css/Article-List-1.css' %}">
    <link rel="stylesheet" href="{% static 'css/Article-List.css' %}">
    <link rel="stylesheet" href="{% static 'css/Footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/Header.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-md menu">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:home' %}">
                <img src="{% static 'img/edcar-logo.png' %}" style="width: 180px;">
            </a>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-3">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navcol-3">
                <ul class="nav navbar-nav mx-auto">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link submenu" href="{% url 'core:home' %}" style="font-weight: bold;">Home</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" href="{% url 'core:quem_somos' %}" style="font-weight: bold;">Quem Somos</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" href="{% url 'core:contato' %}" style="font-weight: bold;">Contato</a>
                    </li>
                </ul>
                <span class="navbar-text">
                    <a class="login" href="/admin" style="color: rgb(255,255,255);font-weight: normal;">Acesso Restrito</a>
                </span>
            </div>
        </div>
    </nav>

    <div class="container" style="max-width:1700px;">
        {% block content %}
        {% endblock %}
    </div>

    <div class="footer-basic">
        <footer>
            <div class="social"><a href="https://www.instagram.com/edcar_distribuidora/?hl=pt-br" target="_blank"><i class="icon ion-social-instagram"></i></a><a href="#" target="_blank"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="{% url 'core:home' %}">Home</a></li>
                <li class="list-inline-item"><a href="{% url 'core:quem_somos' %}">Quem Somos</a></li>
                <li class="list-inline-item"><a href="{% url 'core:contato' %}">Contato</a></li>
            </ul>
            <p class="copyright">Ed Car © 2020</p>
        </footer>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

edcar_distribuidora/templates/pages/about.html
{% extends "base.html" %}

edcar_distribuidora/templates/pages/home.html
{% extends "base.html" %}

edcar_distribuidora/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

edcar_distribuidora/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}